# Generated by Django 2.2.19 on 2021-03-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='サイズ',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
