# Generated by Django 2.2.19 on 2021-03-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0004_auto_20210314_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='defo', upload_to='documents/'),
        ),
    ]
