# Generated by Django 2.2.19 on 2021-03-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0005_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名前', models.CharField(max_length=20)),
            ],
        ),
    ]
