# Generated by Django 2.2.19 on 2021-03-19 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0006_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='着数',
            new_name='数量',
        ),
    ]
