# Generated by Django 2.2.19 on 2021-03-19 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0007_auto_20210319_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='合計価格',
        ),
    ]
