# Generated by Django 2.2.19 on 2021-05-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0009_auto_20210501_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='数量',
            field=models.IntegerField(blank=True, default=True, help_text='商品を登録する際は空白にしてください。'),
        ),
    ]
