# Generated by Django 2.2.19 on 2021-05-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0010_auto_20210501_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='数量',
            field=models.IntegerField(default=0, help_text='商品を登録する際は0にしてください。'),
        ),
    ]
