# Generated by Django 2.2.19 on 2021-05-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0011_auto_20210501_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('品名', models.CharField(max_length=20)),
                ('品番', models.CharField(max_length=20)),
                ('価格', models.IntegerField()),
                ('サイズ', models.CharField(max_length=20)),
                ('数量', models.IntegerField()),
                ('小計', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='products',
        ),
        migrations.AddField(
            model_name='offer',
            name='purchased_products',
            field=models.ManyToManyField(to='ordersite.PurchasedProduct'),
        ),
    ]
