# Generated by Django 2.2.19 on 2021-05-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0012_auto_20210501_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(to='ordersite.Product'),
        ),
    ]
