# Generated by Django 2.2.19 on 2021-09-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0014_auto_20210501_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(to='ordersite.Product'),
        ),
    ]
