# Generated by Django 2.2.19 on 2021-09-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0015_offer_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('購入者', models.CharField(max_length=20, null=True)),
                ('メールアドレス', models.EmailField(max_length=254, null=True)),
                ('purchased_products', models.ManyToManyField(to='ordersite.PurchasedProduct')),
            ],
        ),
    ]
