# Generated by Django 2.2.19 on 2021-09-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0016_purchaser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaser',
            name='purchased_products',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='products',
        ),
        migrations.DeleteModel(
            name='PurchasedProduct',
        ),
        migrations.DeleteModel(
            name='Purchaser',
        ),
    ]
