# Generated by Django 2.2.19 on 2021-11-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0019_auto_20210920_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='日付',
            field=models.DateField(blank=True, null=True),
        ),
    ]
