# Generated by Django 2.2.19 on 2021-11-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0020_offer_日付'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['the_order']},
        ),
        migrations.AddField(
            model_name='product',
            name='the_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
