# Generated by Django 2.2.19 on 2021-11-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0021_auto_20211105_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='小計_表示用',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
