# Generated by Django 2.2.19 on 2021-12-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersite', '0022_offer_小計_表示用'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='アーカイブ',
            field=models.BooleanField(null=True),
        ),
    ]
